#!/bin/sh

stylefile=$INPUT_STYLE_FILE
directory=$INPUT_DIRECTORY

if [ -z "$directory" ]; then
	directory='.'
fi

if [ -n "$stylefile" ]; then
	mdl --style "$GITHUB_WORKSPACE/$stylefile" $directory
else
	mdl $directory
fi
